spring:
  datasource:
    default:
      jdbc-url: jdbc:sqlite:C:/water/database.db
      driver-class-name: org.sqlite.JDBC
    pg:
      jdbc-url: jdbc:postgresql://localhost:5432/water?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123

databaseSelect: sqlite
jsonAddress: C:/water/config.json
dateAddress: C:/water/date.json