spring:
  application:
    name: tide-flow
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  task:
    scheduling:
      pool:
        size: 5
server:
  port: 9933