spring:
  datasource:
    default:
      jdbc-url: jdbc:sqlite:D:/zhuomian/water/database.db
      driver-class-name: org.sqlite.JDBC
    pg:
      jdbc-url: jdbc:postgresql://localhost:5432/water?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123

databaseSelect: sqlite
jsonAddress: E:/github/schedule-tide-flow/config.json
dateAddress: E:/github/schedule-tide-flow/date.json

tideUrl: http://localhost:9999/tide/pushData
flowUrl: http://localhost:9999/flow/pushData